AWSTemplateFormatVersion: '2010-09-09'
Description: 'Automated BLESS CFN by sethkor'

# Input Parameters
Parameters:
  ami:
    Type: String
    Description: The AMI id to use
  iamprofile:
    Type: String
    Description: The IAM instance profile for the bastion.
  key:
    Type: String
  kmskey:
    Type: String
    Description: Your kms key id
  subnets:
    Type: CommaDelimitedList
    Description: The List of subnets to attempt to launch a bastion host in.
  password:
    Type: String
    Description: Password for your key.
    NoEcho: true 
  user:
    Type: String
    Description: The user this bastion is for.   
  vpc:
    Type: String
    Description: The VPC ID for the Bastion host, usually the cloud ops build VPC
  yourcidr:
    Type: String
    Description: The CIDR fromwhich you are connecting to the Bastion   
    
Resources:

#
# Create an Elastic IP for your bastion.  This will mean if you terminate your bastion and
# it is recreated via the auto scaling group it will always have the same public IP
#
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref vpc

#
# Security group for bastion access.  It will allow access from you IP
#
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [-, [bastion-sg, !Ref user]]
      GroupDescription: Enable SSH access to bastion via port 22
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref yourcidr
      Tags:
        - Key: Name
          Value: !Join [-, [bastion-sg, !Ref user]]

#
# Autoscaling group for the Bastion.  Make sure there is always 1 bastion running
#
  BastionAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      LaunchConfigurationName: !Ref BastionLc
      MaxSize: 1
      MinSize: 1
      Tags:
        -
          Key: node
          Value: bastion
          PropagateAtLaunch: true
        -
          Key: Name
          Value: !Join ['',[bastion-, !Ref user]]
          PropagateAtLaunch: true
        -
          Key: User
          Value: !Ref user
          PropagateAtLaunch: true
      VPCZoneIdentifier: !Ref subnets

#
# Launch config for the Bastion.  It will generate a new set of keys and publish the
# lambda each time a new bastion is created via the Auto Scaling Group.  KeyName is 
# commented out as it's not needed unlessss you are trying to debug bless config on 
# the bastion.  If you enable it it can lead to false positives when testing and using
# BLESS.  if you uncomment it be sure to add a key value in the env.mk file
#
  BastionLc:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref iamprofile
      ImageId: !Ref ami
      InstanceType: t2.micro
#      KeyName: !Ref key
      SecurityGroups:
        - !GetAtt BastionSecurityGroup.GroupId
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo -i -u ec2-user /bin/bash -xe << 'EOF'
          cd bless
          python3.7 -m venv venv
          source venv/bin/activate
          ssh-keygen -t rsa -b 4096 -f bless-ca -C "SSH CA Key" -N ${password}
          /usr/bin/credstash -r ${AWS::Region} delete bless-ca.pem
          /usr/bin/credstash -r ${AWS::Region} delete bless-ca.pub 
          /usr/bin/credstash -r ${AWS::Region} put -k ${kmskey} bless-ca.pem @bless-ca
          /usr/bin/credstash -r ${AWS::Region} put -k ${kmskey} bless-ca.pub @bless-ca.pub
          aws kms encrypt --region ${AWS::Region} --key-id ${kmskey} --plaintext ${password} --output text --query CiphertextBlob > YourKmsEncryptedPassword.kms
          cp bless/config/bless_deploy_example.cfg bless/config/bless_deploy.cfg
          sed -i 's|us-east-1_password = <INSERT_US-EAST-1_KMS_ENCRYPTED_BASE64_ENCODED_PEM_PASSWORD_HERE>|# |g' bless/config/bless_deploy.cfg
          sed -i "s|us-west-2_password = <INSERT_US-WEST-2_KMS_ENCRYPTED_BASE64_ENCODED_PEM_PASSWORD_HERE>|default_password = $(cat YourKmsEncryptedPassword.kms)|g" bless/config/bless_deploy.cfg
          sed -i 's|<INSERT_YOUR_ENCRYPTED_PEM_FILE_NAME>|bless-ca|g' bless/config/bless_deploy.cfg
          mkdir lambda_configs
          cp bless-ca ./lambda_configs/
          chmod 444 ./lambda_configs/bless-ca
          cp bless/config/bless_deploy.cfg ./lambda_configs/
          make publish
          aws s3 cp publish/bless_lambda.zip s3://${LambdaBucket}
          lambdaExists=$(aws lambda list-functions --region ${AWS::Region} --query 'Functions[?FunctionName==`blesskor-bastion`]' --output text)
          if [ "$lambdaExists" != "" ]; then aws lambda delete-function --region ${AWS::Region} --function-name blesskor-bastion; fi
          aws lambda create-function --region ${AWS::Region} --function-name blesskor-bastion --runtime python3.6 --timeout 10 --role arn:aws:iam::${AWS::AccountId}:role/BastionLambdaIamRole --handler bless_lambda.lambda_handler --code S3Bucket=${LambdaBucket},S3Key=bless_lambda.zip
          aws s3 rm s3://${LambdaBucket}/bless_lambda.zip
          EOF
          echo -e '\nTrustedUserCAKeys /etc/ssh/cas.pub' >> /etc/ssh/sshd_config
          cat /home/ec2-user/bless/bless-ca.pub > /etc/ssh/cas.pub
          sudo service sshd restart
          aws ec2 associate-address --region ${AWS::Region} --instance-id $(curl -s -m 60 http://169.254.169.254/latest/meta-data/instance-id) --allocation-id ${EIP.AllocationId}
          cd ..
          rm -rf bless

#
# Bucket to push Lambda zip
#

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

Outputs:
  BastionIp:
   Description: The Public EIP for the Bastion
   Value: !Ref EIP 

